spring.datasource.url=jdbc:mysql://localhost:3306/pulseup?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Johannesburg
spring.datasource.username=root
spring.datasource.password=tiyani

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false