spring.application.name=PulseUp2026

spring.datasource.url=jdbc:mysql://localhost:3306/pulseup?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Africa/Johannesburg
spring.datasource.username=${PULSEUP_DB_USERNAME}
spring.datasource.password=${PULSEUP_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=${PULSEUP_JWT_SECRET}
security.jwt.issuer=pulseup-api
security.jwt.expiration-seconds=3600




